### ISSUE TITLE
Use public domain or Creative Commons media

### ISSUE THREAD

**Issue by petecooper** [textpattern/unit-test#1]
Not for now, but we should use 'safe' images where viable.

**Comment by Bloke** [comment]
Good point. Swapped out. Sorry for stomping on your optim.

**Comment by petecooper** [comment]
Missed one - `7.gif` and its thumbnail.

**Comment by Bloke** [comment]
Sigh. `git rm images/*.png` didn't remove gifs too. Why can't the command line just _know_ what I meant to do :D 

Fixed, thank you.
